name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/ZBugar75.PlayersWallet.sln
    - name: Build
      run: dotnet build --no-restore src/ZBugar75.PlayersWallet/ZBugar75.PlayersWallet.Api.csproj
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
